/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/**
 *
 * @author matth
 */
public class userinterface extends javax.swing.JFrame {
    public String sbrand,smodel;
    int a=0;
    int model_toyota=5;
    int model_mercedes=8;
    int model_bmw=3;
    ImageIcon icon_m,icon_t,icon_b,icon_a;
    finder modelscanner;
    test1 imgctr;
    public userinterface() throws Exception {
        initComponents();
        modelscanner=new finder();
        imgctr=new test1();
        modelscanner.Apply("Brand"," "," ");
        for (int i = 0; i <modelscanner.brands.size() ; i++) {
            brand.addItem(modelscanner.brands.get(i));
        }
    }
    ImageIcon imageIcon;
    void sizer(){
            imageIcon = new ImageIcon(imgctr.path); // load the image to a imageIcon
            Image image = imageIcon.getImage(); // transform it 
            Image newimg = image.getScaledInstance(180, 90,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
            imageIcon = new ImageIcon(newimg);  // transform it back
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        model = new javax.swing.JComboBox<>();
        modelimg = new javax.swing.JLabel();
        brandimg = new javax.swing.JLabel();
        brand = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        piece = new javax.swing.JComboBox<>();
        dealer = new javax.swing.JComboBox<>();
        number = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        model.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Model" }));
        model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelActionPerformed(evt);
            }
        });

        modelimg.setText("Model");

        brandimg.setText("Brand");

        brand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brand" }));
        brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandActionPerformed(evt);
            }
        });

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year" }));
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        piece.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Piece" }));
        piece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieceActionPerformed(evt);
            }
        });

        dealer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dealer" }));
        dealer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealerActionPerformed(evt);
            }
        });

        number.setText("Dealer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(brand, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(brandimg, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(model, 0, 144, Short.MAX_VALUE)
                    .addComponent(modelimg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(piece, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dealer, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dealer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(piece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modelimg, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brandimg, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelActionPerformed
        if(model.hasFocus()){
           
            modelscanner.Apply("Year",(String)model.getSelectedItem().toString()," ");
            
             try {
            imgctr.ImageControl((String)brand.getSelectedItem().toString(),(String)model.getSelectedItem().toString());
            sizer();
            modelimg.setText("");
            modelimg.setIcon(imageIcon);
            imgctr.DeleteImage(imgctr.path);
            
        } catch (IOException ex) {
            Logger.getLogger(userinterface.class.getName()).log(Level.SEVERE, null, ex);
        }
            year.removeAllItems();
            for (int i = 0; i <  modelscanner.years.size(); i++) {
                year.addItem( modelscanner.years.get(i));
            }
        }
        
    }//GEN-LAST:event_modelActionPerformed

    private void brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandActionPerformed
        
        model.removeAllItems();
        String brandstr=brand.getSelectedItem().toString();
        try {
            imgctr.ImageControl(brandstr,brandstr);
            sizer();
            brandimg.setText("");
            brandimg.setIcon(imageIcon);
            imgctr.DeleteImage(imgctr.path);
            
        } catch (IOException ex) {
            Logger.getLogger(userinterface.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        System.out.println(brandstr);
        if("Brand".equals(brandstr)){
            brand.removeAllItems();
            brand.addItem("Brand");
            modelscanner.Apply("Brand"," "," ");
            for (int i = 0; i <modelscanner.brands.size() ; i++) {
            brand.addItem(modelscanner.brands.get(i));
        }
        }else{
            modelscanner.Apply("Model",brandstr," ");
            for (int i = 0; i <  modelscanner.models.size(); i++) {
                model.addItem( modelscanner.models.get(i));
           }
        }
       

       
       

    }//GEN-LAST:event_brandActionPerformed

    private void pieceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieceActionPerformed
        if(piece.hasFocus()){
            String s=brand.getSelectedItem().toString()+model.getSelectedItem().toString();
            s=s+year.getSelectedItem().toString()+piece.getSelectedItem().toString();
            System.out.println(s);
            modelscanner.Apply("Dealer",s," ");  
            dealer.removeAllItems();
           for (int i = 0; i < modelscanner.dealer.size(); i++) {
                dealer.addItem(modelscanner.dealer.get(i));
            }
        }
    }//GEN-LAST:event_pieceActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        
        if(year.hasFocus()){
           modelscanner.Apply("PieceName",year.getSelectedItem().toString(),model.getSelectedItem().toString());  
            piece.removeAllItems();
           for (int i = 0; i < modelscanner.piecenames.size(); i++) {
                piece.addItem(modelscanner.piecenames.get(i));
            }
        }
    }//GEN-LAST:event_yearActionPerformed

    private void dealerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dealerActionPerformed
        // TODO add your handling code here:
        if(dealer.hasFocus()){
            number.setText("number of :"+dealer.getSelectedItem().toString());
        }
        
        
    }//GEN-LAST:event_dealerActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new userinterface().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(userinterface.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> brand;
    private javax.swing.JLabel brandimg;
    private javax.swing.JComboBox<String> dealer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> model;
    private javax.swing.JLabel modelimg;
    private javax.swing.JLabel number;
    private javax.swing.JComboBox<String> piece;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
